const express = require("express")
const cookieParser = require("cookie-parser")
const authRoutes = require("./routes/auth.routes")
const musicRoutes = require("./routes/music.routes")
const app = express()
app.use(cookieParser())
app.use(express.json())
app.use("/auth/api", authRoutes)
app.use("/music/api", musicRoutes)
module.exports = app